#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := coaps

EXTRA_COMPONENT_DIRS = $(SQUIDWARD_PATH)/components/sq_wifi
EXTRA_COMPONENT_DIRS += $(SQUIDWARD_PATH)/components/sq_coap
EXTRA_COMPONENT_DIRS += $(SQUIDWARD_PATH)/components/sq_uart

include $(IDF_PATH)/make/project.mk

