#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := coaps_fota

EXTRA_COMPONENT_DIRS = $(SQUIDWARD_PATH)/components/sq_wifi
EXTRA_COMPONENT_DIRS += $(SQUIDWARD_PATH)/components/sq_coap

include $(IDF_PATH)/make/project.mk

